modality: 'all'
priv_modalities: ['state']
action_dim: 4
action_repeat: 1
discount: 0.9
episode_length: 50
train_steps: 50000
offline_steps: 20000
max_buffer_size: 10000
expectile: 0.9
A_scaling: 3.0
iterations: 6
uncertainty_cost: 1
eval_freq: 2000
save_freq: 200000
eval_episodes: 40
offline_model_path: None
filter_demos: false