modality: 'all'
priv_modalities: ['state']
action_repeat: 1
discount: 0.9
episode_length: 50
train_steps: 100000
offline_steps: 25000
max_buffer_size: 10000
expectile: 0.9
A_scaling: 3.0
iterations: 6
uncertainty_cost: 1
dataset_dir: 'data/gymnasium_xarm_lift_medium'
eval_freq: 1000
save_freq: 50000
eval_episodes: 40